version: '2'
services:

  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/
    links:
      -  db

  db:
    image: mysql:latest
    container_name: "mysql_db"
    environment:
      MYSQL_ROOT_PASSWORD: 2401
      MYSQL_DATABASE: phpDB
    ports:
      - "3306"
    
